<?xml version="1.0"?>
<robot name="waiterobot" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="width" value="0.2" />
    <xacro:property name="head_radius" value="0.25" />
    <xacro:property name="head_len" value="0.4" />
    <xacro:property name="hair_len" value="0.07" />
    <xacro:property name="base_thickness" value="0.2" />
    <xacro:property name="base_len" value="0.5" />
    <xacro:property name="body_height" value="0.6" />
    <xacro:property name="legs_height" value="1.0" />
    <xacro:property name="pi" value="3.14159265" />

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="skin_color">
        <color rgba="0.925 0.737 0.706 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
        <mass value="${mass}" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>
    
    <link name="base_link">
      <visual>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
        <geometry>
          <box size="${base_len} ${base_len} ${base_thickness}"/>
        </geometry>
        <material name="white"/>
      </visual>
    </link>

    <joint name="base_to_legs" type="revolute">
      <axis xyz="0 0 1"/>
      <limit lower="0.0" upper="${pi/4.0}" effort="50.0" velocity="0.5"/>
      <parent link="base_link"/>
      <child link="legs_link"/>
    </joint>

    <link name="legs_link">
      <visual>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 ${base_thickness+0.2}"/>
        <geometry>
          <!-- <cylinder radius="${width}" length="${legs_height}"/> -->
          <box size="${width} ${width*2.4} ${legs_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <!-- <cylinder radius="${width}" length="${legs_height}"/> -->
          <box size="${width} ${width*2.4} ${legs_height}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="10"/>
    </link>

    <joint name="legs_to_body" type="revolute">
      <axis xyz="1 0 0"/>
      <limit lower="0.0" upper="${pi/16.0}" effort="50.0" velocity="0.5"/>
      <parent link="legs_link"/>
      <child link="body_link"/>
    </joint>

    <link name="body_link">
      <visual>
        <origin xyz="0.2 0.0 ${legs_height}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <!-- <cylinder radius="${width}" length="${body_height}"/> -->
          <box size="${width} ${width} ${body_height}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <geometry>
          <box size="${width} ${width} ${body_height}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="10"/>
    </link>

    <joint name="body_to_head" type="fixed">
      <parent link="body_link"/>
      <child link="head_link"/>
      <origin xyz="0 0 0"/>
    </joint>

    <link name="head_link">
      <visual>
        <origin xyz="0.2 0.0 ${legs_height+body_height-0.2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder length="${head_len}" radius="${head_radius}"/>
        </geometry>
        <material name="skin_color"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${head_len}" radius="${head_radius}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="4"/>
    </link>

    <joint name="head_to_hair" type="fixed">
      <parent link="head_link"/>
      <child link="hair_link"/>
      <origin xyz="0 0 0"/>
    </joint>

    <link name="hair_link">
      <visual>
        <origin xyz="0.2 0.0 ${legs_height+body_height+0.05}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder length="${hair_len}" radius="${head_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <box size="${width} ${width} ${body_height}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="4"/>
    </link>
</robot>