# The joint state controller handles publishing transforms for any moving joints
type: "joint_state_controller/JointStateController"
publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_to_legs

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: legs_to_body
